

services:
  web:
    build:
      context: ./apps/web-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api

  api:
    build:
      context: .  # Use the root project folder as the context
      dockerfile: ./services/api/Dockerfile # Tell it where to find the Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://db:27017}
      - MONGO_DB=${MONGO_DB:-learnquest}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      - CHROMA_HOST=${CHROMA_HOST:-chroma}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
    depends_on:
      - chroma-init
      - seed
    restart: unless-stopped

  # Judge0 dependencies
  judge0-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
    volumes:
      - judge0_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  judge0-redis:
    image: redis:7-alpine
    restart: unless-stopped

  judge0:
    image: judge0/judge0:1.13.0
    ports:
      - "2358:2358"
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_HOST=judge0-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - DISABLE_SANDBOX=true
      - ENABLE_WAIT_RESULT=true
      - ENABLE_COMPILER_OPTIONS=true
    depends_on:
      - judge0-db
      - judge0-redis
    restart: unless-stopped
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  judge0-worker:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    environment:
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_HOST=judge0-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - DISABLE_SANDBOX=true
    depends_on:
      - judge0
      - judge0-db
      - judge0-redis
    restart: unless-stopped
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  seed:
    image: python:3.10-slim
    volumes:
      - ./scripts:/app/scripts
      - ./services/api/src:/app/services/api/src
    working_dir: /app
    command: >
      sh -c "pip install pymongo passlib[bcrypt] python-jose[cryptography] && python /app/scripts/seed_db.py"
    depends_on:
      - db
    restart: "no"

  db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    restart: unless-stopped

  chroma-init:
    image: python:3.10-slim
    volumes:
      - ./scripts:/app/scripts
    working_dir: /app
    command: >
      sh -c "sleep 30 && pip install chromadb && python /app/scripts/init_chroma.py"
    depends_on:
      - chroma
    restart: "no"

volumes:
  mongo_data:
  judge0_pg_data:
  chroma_data:

networks:
  default:
    name: learnquest-network
